# permissions for end users to view appregistrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appregistration-viewer-role
rules:
- apiGroups:
  - aum.my.domain
  resources:
  - appregistrations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aum.my.domain
  resources:
  - appregistrations/status
  verbs:
  - get
